# Generated by Django 3.2.7 on 2021-09-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_imgage',
            field=models.ImageField(null=True, upload_to='myimage'),
        ),
    ]
