# Generated by Django 3.2.7 on 2021-09-22 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_post_post_imgage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_imgage',
            new_name='post_image',
        ),
    ]
