# Generated by Django 3.2.7 on 2021-09-22 14:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_post_imgage_post_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
